### ISSUE TITLE
バックエンドAPIの要件決定

### ISSUE THREAD

**Issue by equal-l2** [su-its/ams-project#3]

**Comment by equal-l2** [comment]
現状のAPI
- アクセスログの読み出し (`GET /access_logs`)
- カードリーダによる入室処理 (`POST /room`)
- 在室者一覧の読み出し (`GET /users_in_room`)
- 在室確認 (`GET /users_in_room/:userId`)

**Comment by equal-l2** [comment]
気になっていること
- 退室処理できるAPIはいる?（CC: @h-takeyeah）
	- 特定時刻に全員を退室させる、などのユースケース
- フロントエンドに変化を通知する仕組みが必要(WebSocketとか)

**Comment by h-takeyeah** [comment]
私見
退室処理を行うためのAPIの実装はデータベースのリセットがフロントエンド側からできてしまうということと同義なので記録としての信頼性の観点から不要だと思います。たとえ実装するとしても先に認証を挟むことが必要だと思います。

カードタッチ時のイベントをバックエンドからフロントエンドに飛ばす方法についてはwebsocketしかないのでしょう、ということ以上は分かりかねます。

**Comment by equal-l2** [comment]
確かに認証がない現状では外から書き込みができるのは危うさがありますね

**Comment by equal-l2** [comment]
このissueをams-backend-nodejsに転送してよいですか？
